apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./feature-a
  - ./feature-b
images:
  - name: grgate/demo-frontend
    newName: grgate/demo-frontend # {"$imagepolicy": "flux-system:demo-frontend:name"}
    newTag: 5.0.0 # {"$imagepolicy": "flux-system:demo-frontend:tag"}

  - name: grgate/demo-backend
    newName: grgate/demo-backend # {"$imagepolicy": "flux-system:demo-backend:name"}
    newTag: main-c0f5499f71fd711abfa7da97408a0b150627a8ea-5 # {"$imagepolicy": "flux-system:demo-backend:tag"}
