apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./feature-a
  - ./feature-b
images:
  - name: grgate/demo-frontend
    digest: sha256:13fcce55d4dabe08fa4cd8aea04f4a2df646a2b737cdb523145d1cad428ed45d
  - name: grgate/demo-backend
    digest: sha256:57f91d3177f1c6fefa4d03e5b07d57d2b6a42047fe3ebac8ae8b0ca36120f89f
