apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./feature-a
  - ./feature-b
images:
  - name: grgate/demo-frontend
    newTag: latest@sha256:c48f1775138e38c5b84ae1d4dfde52d58876f0ce24011e8caae098a9beec8a57
  - name: grgate/demo-backend
    newTag: latest@sha256:b76ca39385538cbe8dc19be33857b94736828ce5c18b7734c9eeeb1f6a1a472b
