apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: e2e-runner
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get","list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: e2e-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: e2e-runner
subjects:
  - kind: ServiceAccount
    name: e2e-runner
