apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-init
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: e2e-init
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: e2e-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: e2e-init
subjects:
  - kind: ServiceAccount
    name: e2e-init
