apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - namespace.yaml
  - ../bases/backend
  - ../bases/frontend
images:
  - name: grgate/demo-frontend
    digest: v1.0.0
  - name: grgate/demo-backend
    digest: v1.0.0
