apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - namespace.yaml
  - ../bases/backend
  - ../bases/frontend
images:
  - name: grgate/demo-frontend
    newName: grgate/demo-frontend # {"$imagepolicy": "flux-system:demo-frontend-prod:name"}
    newTag: v0.1.1 # {"$imagepolicy": "flux-system:demo-frontend-prod:tag"}
  - name: grgate/demo-backend
    newName: grgate/demo-backend # {"$imagepolicy": "flux-system:demo-backend-prod:name"}
    newTag: v0.1.1 # {"$imagepolicy": "flux-system:demo-backend-prod:tag"}
