apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  strategy:
    type: RollingUpdate
  template:
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: grgate/demo-frontend
          ports:
            - name: http
              containerPort: 8080
            - name: probe
              containerPort: 8090
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: probe
          readinessProbe:
            httpGet:
              path: /
              port: probe

