apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: e2e-post-deploy
spec:
  interval: 30s
  dependsOn:
    - name: e2e-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/e2e/post-deploy
  timeout: 5m
  force: true
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
