apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: e2e-environments
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: backend
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
  path: ./apps/e2e
  timeout: 5m
  prune: true
  wait: true
