apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: e2e-pre-deploy
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/e2e/pre-deploy
  timeout: 5m
  force: true
  prune: true
  wait: true
