apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: e2e
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/e2e
  timeout: 5m
  prune: true
  wait: true
  force: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
