apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/grgate/demo-manifests.git
    targetRevision: HEAD
    path: apps/e2e/feature-a

    kustomize:
      version: v3.5.4

  destination:
    server: https://kubernetes.default.svc
    # namespace: guestbook
