apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: demo-frontend
spec:
  image: grgate/demo-frontend
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: demo-backend
spec:
  image: grgate/demo-backend
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: demo-e2e-runner
spec:
  image: grgate/demo-e2e-runner
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-frontend-prod
spec:
  imageRepositoryRef:
    name: demo-frontend
  filterTags:
    pattern: 'v.*'
  policy:
    semver:
      range: '^v0.x.x'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-backend-prod
spec:
  imageRepositoryRef:
    name: demo-backend
  filterTags:
    pattern: 'v.*'
  policy:
    semver:
      range: '^v0.x.x'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-frontend-e2e
spec:
  imageRepositoryRef:
    name: demo-frontend
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<run>.*)'
    extract: '$run'
  policy:
     numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-backend-e2e
spec:
  imageRepositoryRef:
    name: demo-backend
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<run>.*)'
    extract: '$run'
  policy:
     numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-e2e-runner
spec:
  imageRepositoryRef:
    name: demo-e2e-runner
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<run>.*)'
    extract: '$run'
  policy:
     numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: apps
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: main
    commit:
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}        
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
  interval: 5m
  update:
    strategy: Setters
    path: ./apps/
